# docker-compose -f docker-compose.builder.yml run --rm install|build
version: '2'
services:
  base:
    image: node:11
    volumes:
      - .:/usr/next-web-app
    working_dir: /usr/next-web-app
  install:
    extends:
      service: base
    command: npm i
  build:
    extends:
      service: base
    command: npm run build
